"""empty message

Revision ID: 2206315bf987
Revises: e4d62f6258c9
Create Date: 2021-03-14 23:00:31.130003

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2206315bf987'
down_revision = 'e4d62f6258c9'
branch_labels = None
depends_on = None

SIDES = (
    ('long', 'Long'),
    ('short', 'Short'),
)

TYPES = (
    ('market', 'Market'),
    ('stop', 'Stop'),
)

STATUSES = (
    ('new', 'New'),
    ('filled', 'Filled'),
    ('canceled', 'Canceled'),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soft_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('side', sqlalchemy_utils.types.choice.ChoiceType(SIDES), nullable=True),
    sa.Column('order_type', sqlalchemy_utils.types.choice.ChoiceType(TYPES), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(STATUSES), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
