"""empty message

Revision ID: 2fefff2271fd
Revises: c95de69df9e9
Create Date: 2021-03-14 19:10:30.225959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fefff2271fd'
down_revision = 'c95de69df9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_equities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soft_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_account_historical_equities',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('historical_equity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['historical_equity_id'], ['historical_equities.id'], )
    )
    op.add_column('accounts', sa.Column('cash', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'cash')
    op.drop_table('association_account_historical_equities')
    op.drop_table('historical_equities')
    # ### end Alembic commands ###
