"""empty message

Revision ID: 3ad3336a30e6
Revises: e97dfceb8136
Create Date: 2021-05-07 03:58:21.016023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad3336a30e6'
down_revision = 'e97dfceb8136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_account_positions')
    op.add_column('positions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'positions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'account_id')
    op.create_table('association_account_positions',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='association_account_positions_account_id_fkey'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='association_account_positions_position_id_fkey')
    )
    # ### end Alembic commands ###
