"""empty message

Revision ID: 8518cfcd9ec8
Revises: c2f3275783ae
Create Date: 2021-05-07 02:01:09.986520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8518cfcd9ec8'
down_revision = 'c2f3275783ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('needed_funds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'needed_funds')
    # ### end Alembic commands ###
