"""empty message

Revision ID: 913ce0b5d356
Revises: c633ea23c1b8
Create Date: 2021-05-07 03:28:05.845528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913ce0b5d356'
down_revision = 'c633ea23c1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('orders_account_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'accounts', ['account_id'], ['id'])
    op.drop_column('orders', 'account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('account', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_account_fkey', 'orders', 'accounts', ['account'], ['id'])
    op.drop_column('orders', 'account_id')
    # ### end Alembic commands ###
