"""empty message

Revision ID: a3d0c2c73735
Revises: f8a67ff4291c
Create Date: 2021-03-14 19:41:35.232809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d0c2c73735'
down_revision = 'f8a67ff4291c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_account_positions',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_account_positions')
    # ### end Alembic commands ###
