"""empty message

Revision ID: b3246d6620c7
Revises: bba167394462
Create Date: 2021-05-07 03:20:58.543944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3246d6620c7'
down_revision = 'bba167394462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_account_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_account_orders',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='association_account_orders_account_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='association_account_orders_order_id_fkey')
    )
    # ### end Alembic commands ###
