"""empty message

Revision ID: bba167394462
Revises: 8518cfcd9ec8
Create Date: 2021-05-07 03:02:56.492212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba167394462'
down_revision = '8518cfcd9ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('filled_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'filled_price')
    # ### end Alembic commands ###
