"""empty message

Revision ID: c2f3275783ae
Revises: 91992a5a6ee5
Create Date: 2021-04-25 21:16:40.665627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f3275783ae'
down_revision = '91992a5a6ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'closed')
    # ### end Alembic commands ###
