"""empty message

Revision ID: c633ea23c1b8
Revises: b3246d6620c7
Create Date: 2021-05-07 03:25:18.007528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c633ea23c1b8'
down_revision = 'b3246d6620c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('account', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'accounts', ['account'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'account')
    # ### end Alembic commands ###
