"""empty message

Revision ID: e4d62f6258c9
Revises: a3d0c2c73735
Create Date: 2021-03-14 22:49:34.749541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d62f6258c9'
down_revision = 'a3d0c2c73735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('entry_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'entry_price')
    # ### end Alembic commands ###
