"""empty message

Revision ID: f8a67ff4291c
Revises: 2fefff2271fd
Create Date: 2021-03-14 19:38:05.311184

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'f8a67ff4291c'
down_revision = '2fefff2271fd'
branch_labels = None
depends_on = None

SIDES = (
    ('buy', 'Buy'),
    ('sell', 'Sell'),
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soft_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('side', sqlalchemy_utils.types.choice.ChoiceType(SIDES), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    # ### end Alembic commands ###
