version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - llama-db:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/llama
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: 1

volumes:
  llama-db: {}
  app: {}
